server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'file_logs'
    static_configs:
      - labels:
          job: 'file_logs'
        __path__: /var/log/app/*.log
