openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Получить все задачи
      operationId: GetTasks
      tags:
        - tasks
      responses:
        '200':
          description: Список задач
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Создать новую задачу
      operationId: CreateTask
      tags:
        - tasks
      requestBody:
        description: Новая задача
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      responses:
        '200':
          description: Новая задача
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Некорректный запрос
        '422':
          description: Неверное тело запроса
        '500':
          description: Ошибка добавления задачи
  /tasks/{id}:
    get:
      summary: Получить задачу по ID
      tags:
        - tasks
      operationId: GetTaskByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: Задача по ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Задача не найдена
        '500':
          description: Ошибка поиска задачи
    patch:
      tags:
        - tasks
      summary: Обновить задачу по ID
      operationId: UpdateTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: Обновленная задача
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Неверный формат запроса
        '422':
          description: Неверные данные
        '404':
          description: Задача не найдена
        '500':
          description: Ошибка обновления задачи
    delete:
      summary: Удалить задачу по ID
      tags:
        - tasks
      operationId: DeleteTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '204':
          description: Задача успешно удалена
        '404':
          description: Задача не найдена
        '500':
          description: Ошибка удаления задачи
  /users/{user_id}/tasks/:
    get:
      summary: Получить задачи конкретного пользователя
      tags:
        - tasks
      operationId: GetTasksByUserID
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: Список задач
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Ошибка получения задач пользователя
  /users:
    get:
      summary: Получить всех пользователей
      tags:
        - users
      operationId: GetUsers
      responses:
        '200':
          description: Список пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsersResponse'
    post:
      summary: Добавить нового пользователя
      operationId: CreateUser
      tags:
        - users
      requestBody:
        description: Новый пользователь
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '200':
          description: Новый пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
        '400':
          description: Некорректный запрос
        '422':
          description: Пользователь с таким email уже существует
        '500':
          description: Ошибка добавления пользователя
  /users/{id}:
    get:
      summary: Получить данные пользователя
      operationId: GetUserById
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
        '404':
          description: Пользователь не найден
        '500':
          description: Ошибка при получении пользователя
    patch:
      summary: Обновить данные пользователя
      operationId: UpdateUser
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        '200':
          description: Обновленный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
        '400':
          description: Некорректный запрос
        '422':
          description: Пользователь с таким email уже существует
        '500':
          description: Ошибка обновления данных пользователя
    delete:
      summary: Удалить пользователя
      operationId: DeleteUserById
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '204':
          description: Пользователь успешно удален
        '404':
          description: Пользователь не найден
        '500':
          description: Ошибка удаления пользователя

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: uint
        task:
          type: string
        is_done:
          type: boolean
        user_id:
          type: integer
          format: uint
      required:
        - id
        - task
    CreateTask:
      type: object
      properties:
        task:
          type: string
        user_id:
          type: integer
          format: uint
      required:
        - task
        - user_id
    UpdateTask:
      type: object
      properties:
        task:
          type: string
        is_done:
          type: boolean
    UsersResponse:
      type: object
      properties:
        id:
          type: integer
          format: uint
        email:
          type: string
          format: email
      required:
        - id
        - email
    CreateUser:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    UpdateUser:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string